// Recurring + signature characters across the King universe. The point
// is the cross-book links — Father Callahan in Salem's Lot AND Dark
// Tower V, Randall Flagg in seven books, Holly Gibney in five, etc.

export type Character = {
  name: string;
  aliases?: string[];
  role: string;            // single-line who-they-are
  description: string;     // longer paragraph
  books: string[];         // book titles where they appear
  alignment?: "protagonist" | "antagonist" | "neutral" | "supernatural";
};

export const characters: Character[] = [
  // The Big Bads
  { name: "Randall Flagg", aliases: ["The Man in Black", "Walter o'Dim", "Walter Padick", "Marten Broadcloak", "Richard Fannin", "Russell Faraday", "The Walkin Dude"],
    role: "King's recurring antagonist",
    description: "The thread that ties the King multiverse together. Sorcerer, demagogue, agent of chaos. Different name, same grin.",
    books: ["The Stand", "The Eyes of the Dragon", "The Dark Tower: The Gunslinger", "The Drawing of the Three", "The Waste Lands", "Wizard and Glass", "The Dark Tower"],
    alignment: "antagonist" },

  { name: "Pennywise", aliases: ["IT", "Bob Gray", "The Deadlights"],
    role: "The clown in the drains",
    description: "An ancient extradimensional entity that feeds on fear, surfacing every 27 years in Derry, Maine. Prefers the form of a clown because clowns terrify children faster.",
    books: ["IT"],
    alignment: "antagonist" },

  { name: "Annie Wilkes",
    role: "The number one fan",
    description: "Retired nurse, novel collector, and prolific killer. The cobbler scene. The sledgehammer.",
    books: ["Misery"],
    alignment: "antagonist" },

  { name: "Jack Torrance",
    role: "Father, writer, caretaker",
    description: "Alcoholic novelist who takes a winter caretaker job at the Overlook Hotel. The hotel wants his son. He starts agreeing.",
    books: ["The Shining"],
    alignment: "protagonist" },

  { name: "Leland Gaunt",
    role: "The shopkeeper",
    description: "Opens Needful Things in Castle Rock. Every customer wants something. Payment is always a small favor against a neighbor.",
    books: ["Needful Things"],
    alignment: "antagonist" },

  { name: "Kurt Barlow",
    role: "The vampire of Jerusalem's Lot",
    description: "Centuries-old master vampire who moves into the Marsten House and converts the town one neighbor at a time.",
    books: ["'Salem's Lot"],
    alignment: "antagonist" },

  { name: "John Rainbird",
    role: "The Shop's tracker",
    description: "Mute Native American assassin obsessed with Charlie McGee. Believes the soul of whoever he kills enters him.",
    books: ["Firestarter"],
    alignment: "antagonist" },

  { name: "Brady Hartsfield", aliases: ["Mr. Mercedes"],
    role: "The Mercedes killer",
    description: "Drove a stolen Mercedes into a crowd. Returns in two more books after Bill Hodges hunts him down.",
    books: ["Mr. Mercedes", "Finders Keepers", "End of Watch"],
    alignment: "antagonist" },

  // The Dark Tower core
  { name: "Roland Deschain", aliases: ["The Gunslinger"],
    role: "The last gunslinger of Gilead",
    description: "Hunts the Tower across a moved-on world. Two guns made from Excalibur's metal. Loses fingers along the way.",
    books: ["The Dark Tower: The Gunslinger", "The Drawing of the Three", "The Waste Lands", "Wizard and Glass", "Wolves of the Calla", "Song of Susannah", "The Dark Tower"],
    alignment: "protagonist" },
  { name: "Eddie Dean",
    role: "The Prisoner",
    description: "Heroin addict drawn from 1980s New York. Becomes the second gunslinger. Marries Susannah.",
    books: ["The Drawing of the Three", "The Waste Lands", "Wizard and Glass", "Wolves of the Calla", "Song of Susannah", "The Dark Tower"],
    alignment: "protagonist" },
  { name: "Susannah Dean", aliases: ["Odetta Holmes", "Detta Walker", "Mia"],
    role: "The Lady of Shadows",
    description: "Drawn from 1960s civil-rights New York. Two personalities at first. Sometimes three.",
    books: ["The Drawing of the Three", "The Waste Lands", "Wizard and Glass", "Wolves of the Calla", "Song of Susannah", "The Dark Tower"],
    alignment: "protagonist" },
  { name: "Jake Chambers",
    role: "The Pusher's victim",
    description: "Boy from 1970s New York pushed in front of a car. Pulled into Roland's world. Twice.",
    books: ["The Dark Tower: The Gunslinger", "The Waste Lands", "Wizard and Glass", "Wolves of the Calla", "Song of Susannah", "The Dark Tower"],
    alignment: "protagonist" },
  { name: "Father Callahan",
    role: "The defrocked priest",
    description: "Catholic priest from Jerusalem's Lot who tangled with Barlow, lost, and ran. Reappears in Wolves of the Calla as the keeper of Black Thirteen.",
    books: ["'Salem's Lot", "Wolves of the Calla", "Song of Susannah", "The Dark Tower"],
    alignment: "protagonist" },

  // The Stand
  { name: "Stu Redman",
    role: "Survivor of Captain Trips",
    description: "Texas factory worker. One of the immune. Stands with Mother Abagail against Flagg.",
    books: ["The Stand"],
    alignment: "protagonist" },
  { name: "Mother Abagail Freemantle",
    role: "108-year-old visionary",
    description: "Hand of God in The Stand. Calls the survivors to Boulder.",
    books: ["The Stand"],
    alignment: "protagonist" },
  { name: "Larry Underwood",
    role: "One-hit-wonder pop singer",
    description: "Walks across an empty America. Hears voices in the Lincoln Tunnel.",
    books: ["The Stand"],
    alignment: "protagonist" },
  { name: "Trashcan Man", aliases: ["Donald Merwin Elbert"],
    role: "Pyromaniac apostle",
    description: "Lights fires across the empty Midwest on his way to Vegas to bring Flagg \"a present.\"",
    books: ["The Stand"],
    alignment: "neutral" },
  { name: "Tom Cullen",
    role: "M-O-O-N",
    description: "Developmentally disabled survivor, spells everything M-O-O-N. Walks back from Vegas as a hypnotized spy.",
    books: ["The Stand"],
    alignment: "protagonist" },
  { name: "Harold Lauder",
    role: "Resentful teen",
    description: "Frannie's neighbor. Writes a manifesto. Picks the wrong side.",
    books: ["The Stand"],
    alignment: "antagonist" },
  { name: "Nadine Cross",
    role: "Flagg's intended bride",
    description: "Walked the Boulder side, ended up on the Vegas side, ended up insane.",
    books: ["The Stand"],
    alignment: "antagonist" },

  // IT — the Losers Club
  { name: "Bill Denbrough", aliases: ["Big Bill", "Stuttering Bill"],
    role: "Losers Club leader",
    description: "Lost his brother Georgie to Pennywise. Returns to Derry 27 years later as a horror novelist (sound familiar).",
    books: ["IT"],
    alignment: "protagonist" },
  { name: "Beverly Marsh",
    role: "Only girl in the Losers Club",
    description: "Grows up out of Derry into a fashion designer; comes back when Mike calls. Married to a worse man than her father.",
    books: ["IT"],
    alignment: "protagonist" },
  { name: "Richie Tozier",
    role: "Trashmouth",
    description: "Voices, jokes, the deepest fear. Becomes a stand-up comic in LA.",
    books: ["IT"],
    alignment: "protagonist" },
  { name: "Ben Hanscom",
    role: "The new kid",
    description: "Overweight child who designs the clubhouse. Grows into a celebrated architect.",
    books: ["IT"],
    alignment: "protagonist" },
  { name: "Mike Hanlon",
    role: "The lighthouse keeper",
    description: "Only Loser who stays in Derry. Becomes the town librarian. Makes the call when IT wakes up.",
    books: ["IT"],
    alignment: "protagonist" },
  { name: "Eddie Kaspbrak",
    role: "The hypochondriac",
    description: "Limo driver in adulthood. His inhaler does what he tells it to.",
    books: ["IT"],
    alignment: "protagonist" },
  { name: "Stan Uris",
    role: "The reluctant Loser",
    description: "Boy Scout, ornithologist, can't bring himself to come back to Derry.",
    books: ["IT"],
    alignment: "protagonist" },
  { name: "Henry Bowers",
    role: "Town bully",
    description: "Sociopathic teen with a flick-knife. Survives the kids. Comes back as a man.",
    books: ["IT"],
    alignment: "antagonist" },

  // Shawshank / Green Mile / Misery
  { name: "Andy Dufresne",
    role: "Innocent man at Shawshank",
    description: "Banker, husband, sentenced for a double murder he didn't commit. Patient.",
    books: ["Different Seasons"],
    alignment: "protagonist" },
  { name: "Red", aliases: ["Ellis Boyd Redding"],
    role: "The fixer",
    description: "The man who can get it for you. Lifer. Friend.",
    books: ["Different Seasons"],
    alignment: "protagonist" },
  { name: "John Coffey",
    role: "Death row inmate",
    description: "Huge, gentle, miraculous. \"Like the drink — only not spelled the same.\"",
    books: ["The Green Mile"],
    alignment: "protagonist" },
  { name: "Paul Edgecombe",
    role: "The block boss",
    description: "Narrator. Outlives John, outlives Mr. Jingles. Outlives almost everyone.",
    books: ["The Green Mile"],
    alignment: "protagonist" },
  { name: "Paul Sheldon",
    role: "The captured novelist",
    description: "Best-selling romance writer. Crashes on a Colorado road. Annie saves him; Annie keeps him.",
    books: ["Misery"],
    alignment: "protagonist" },

  // Castle Rock recurrents
  { name: "Alan Pangborn",
    role: "Castle Rock Sheriff",
    description: "Decent man in a town that keeps trying not to be. Pet Sematary spillover. Needful Things end-of-line.",
    books: ["The Dark Half", "Needful Things"],
    alignment: "protagonist" },
  { name: "Pop Merrill",
    role: "Castle Rock junk dealer",
    description: "Buys and sells anything. The Sun Dog reveals just how much he'll keep.",
    books: ["Four Past Midnight", "Needful Things"],
    alignment: "neutral" },
  { name: "Polly Chalmers",
    role: "Seamstress, Alan's love",
    description: "The first sale at Needful Things.",
    books: ["The Dark Half", "Needful Things"],
    alignment: "protagonist" },

  // Dead Zone / Firestarter
  { name: "Johnny Smith",
    role: "Schoolteacher with second sight",
    description: "Wakes from a five-year coma able to read futures by touch. Shakes the wrong hand.",
    books: ["The Dead Zone"],
    alignment: "protagonist" },
  { name: "Greg Stillson",
    role: "Maine politician, future tyrant",
    description: "The hand Johnny doesn't want to shake.",
    books: ["The Dead Zone"],
    alignment: "antagonist" },
  { name: "Charlie McGee",
    role: "Pyrokinetic eight-year-old",
    description: "Daughter of Andy and Vicky McGee, both Lot Six subjects. The Shop wants what she can do.",
    books: ["Firestarter"],
    alignment: "protagonist" },

  // Pet Sematary
  { name: "Louis Creed",
    role: "The man who buries his son",
    description: "Doctor moves family to Ludlow. Doesn't listen to Jud.",
    books: ["Pet Sematary"],
    alignment: "protagonist" },
  { name: "Jud Crandall",
    role: "The neighbor who warns him",
    description: "Old man across the road. Knows about the sour ground past the pet cemetery. Tells anyway.",
    books: ["Pet Sematary"],
    alignment: "neutral" },
  { name: "Gage Creed",
    role: "The toddler",
    description: "Killed by a truck on Route 15. Comes back wrong.",
    books: ["Pet Sematary"],
    alignment: "antagonist" },

  // Bill Hodges trilogy + Holly Gibney
  { name: "Bill Hodges",
    role: "Retired Mid-West detective",
    description: "Three books chasing Brady Hartsfield. Heart trouble. The cigarette he keeps trying not to smoke.",
    books: ["Mr. Mercedes", "Finders Keepers", "End of Watch"],
    alignment: "protagonist" },
  { name: "Holly Gibney",
    role: "The reluctant detective",
    description: "Anxious, brilliant, OCD. Holly meets Bill in Mr. Mercedes, takes over the universe by Holly.",
    books: ["Mr. Mercedes", "Finders Keepers", "End of Watch", "The Outsider", "If It Bleeds", "Holly"],
    alignment: "protagonist" },
  { name: "Jerome Robinson",
    role: "Bill's neighbor kid",
    description: "Mows Bill's lawn. Helps with the chase. Grows up across the trilogy.",
    books: ["Mr. Mercedes", "Finders Keepers", "End of Watch", "Holly"],
    alignment: "protagonist" },

  // 11/22/63
  { name: "Jake Epping", aliases: ["George Amberson"],
    role: "The high-school English teacher who time-travels",
    description: "Steps through a pantry into 1958. Decides to stop Oswald.",
    books: ["11/22/63"],
    alignment: "protagonist" },

  // Doctor Sleep
  { name: "Danny Torrance",
    role: "The boy from the Overlook, grown",
    description: "Recovering alcoholic, hospice worker. Still shines.",
    books: ["The Shining", "Doctor Sleep"],
    alignment: "protagonist" },
  { name: "Abra Stone",
    role: "The girl who shines harder",
    description: "Twelve years old. Stronger than Danny. The True Knot wants her steam.",
    books: ["Doctor Sleep"],
    alignment: "protagonist" },
  { name: "Rose the Hat",
    role: "Leader of the True Knot",
    description: "Top-hatted predator. Eats steam. RV nomad.",
    books: ["Doctor Sleep"],
    alignment: "antagonist" },

  // Christine / Cujo
  { name: "Arnie Cunningham",
    role: "Boy who finds a Plymouth Fury",
    description: "Bullied, friendless, then very much not. The car was always Christine.",
    books: ["Christine"],
    alignment: "protagonist" },
  { name: "Cujo",
    role: "The St. Bernard",
    description: "Bitten by a bat. Rabies takes everything else.",
    books: ["Cujo"],
    alignment: "supernatural" },

  // The Dark Half
  { name: "Thad Beaumont",
    role: "Author with a public pseudonym",
    description: "Killed off his alter ego in print. The alter ego didn't die.",
    books: ["The Dark Half"],
    alignment: "protagonist" },
  { name: "George Stark",
    role: "Thad's pseudonym, made flesh",
    description: "The pen name claws out of the manuscript-burial ceremony. Drives a Toronado.",
    books: ["The Dark Half"],
    alignment: "antagonist" },
];
