// Adaptations of King source material. Tracking the canon — feature
// films + the big TV miniseries. Posters resolve via OMDB's poster URL
// from the IMDB id, fetched by the cover script.

export type Film = {
  title: string;
  year: number;
  type: "film" | "miniseries" | "tv-series";
  director?: string;
  source: string;  // which book / story
  blurb: string;
  imdb?: string;   // imdb tt id — used by OMDB poster lookup
};

export const films: Film[] = [
  { title: "Carrie",                  year: 1976, type: "film",       director: "Brian De Palma",    source: "Carrie",                  blurb: "Pig blood, split screen, Sissy Spacek staring. Set the template for every adaptation that followed.",               imdb: "tt0074285" },
  { title: "'Salem's Lot",            year: 1979, type: "miniseries", director: "Tobe Hooper",        source: "'Salem's Lot",            blurb: "Two nights of CBS, one shot of a kid floating outside a window that scarred a decade.",                              imdb: "tt0079844" },
  { title: "The Shining",             year: 1980, type: "film",       director: "Stanley Kubrick",    source: "The Shining",             blurb: "King hated it. The film won.",                                                                                          imdb: "tt0081505" },
  { title: "Creepshow",               year: 1982, type: "film",       director: "George A. Romero",   source: "Creepshow (original screenplay)", blurb: "Five stories. King wrote them and starred as Jordy Verrill.",                                              imdb: "tt0083767" },
  { title: "The Dead Zone",           year: 1983, type: "film",       director: "David Cronenberg",   source: "The Dead Zone",           blurb: "Walken as Johnny Smith, before \"more cowbell\" was the joke about him.",                                               imdb: "tt0085407" },
  { title: "Christine",               year: 1983, type: "film",       director: "John Carpenter",     source: "Christine",               blurb: "Carpenter's Plymouth Fury. Detroit metal as character.",                                                                imdb: "tt0085333" },
  { title: "Cujo",                    year: 1983, type: "film",       director: "Lewis Teague",       source: "Cujo",                    blurb: "A St. Bernard, a Pinto, an inexplicable PG-13 in a different timeline.",                                                imdb: "tt0085382" },
  { title: "Children of the Corn",    year: 1984, type: "film",       director: "Fritz Kiersch",      source: "Children of the Corn (story)", blurb: "Outlander. He who walks behind the rows. A franchise nobody asked for.",                                          imdb: "tt0087050" },
  { title: "Firestarter",             year: 1984, type: "film",       director: "Mark L. Lester",     source: "Firestarter",             blurb: "Tangerine Dream score. Drew Barrymore at her most laser-eyed.",                                                          imdb: "tt0087262" },
  { title: "Cat's Eye",               year: 1985, type: "film",       director: "Lewis Teague",       source: "Cat's Eye (screenplay)",  blurb: "Three stories tied by a cat. King's screenplay.",                                                                       imdb: "tt0088889" },
  { title: "Silver Bullet",           year: 1985, type: "film",       director: "Daniel Attias",      source: "Cycle of the Werewolf",   blurb: "Corey Haim in a wheelchair-bike vs. a werewolf. Gary Busey is the uncle.",                                                imdb: "tt0090021" },
  { title: "Stand By Me",             year: 1986, type: "film",       director: "Rob Reiner",         source: "The Body",                blurb: "Four kids walk along train tracks looking for a body. The first time everyone agreed King could be tender.",                imdb: "tt0092005" },
  { title: "Maximum Overdrive",       year: 1986, type: "film",       director: "Stephen King",       source: "Trucks (story)",          blurb: "King directed exactly one movie. He was on a lot of cocaine and AC/DC scored it.",                                       imdb: "tt0091499" },
  { title: "The Running Man",         year: 1987, type: "film",       director: "Paul Michael Glaser", source: "The Running Man",        blurb: "Schwarzenegger reads nothing like the book and that's fine.",                                                            imdb: "tt0093894" },
  { title: "Pet Sematary",            year: 1989, type: "film",       director: "Mary Lambert",        source: "Pet Sematary",            blurb: "Toddler walks back. The Ramones wrote the title song.",                                                                  imdb: "tt0098084" },
  { title: "IT",                      year: 1990, type: "miniseries", director: "Tommy Lee Wallace",   source: "IT",                      blurb: "Tim Curry as Pennywise. Two-part ABC miniseries. The CGI spider is the only soft moment.",                                  imdb: "tt0099864" },
  { title: "Misery",                  year: 1990, type: "film",       director: "Rob Reiner",         source: "Misery",                  blurb: "Kathy Bates won the Oscar. Sledgehammer scene survives the ratings.",                                                     imdb: "tt0100157" },
  { title: "Graveyard Shift",         year: 1990, type: "film",       director: "Ralph S. Singleton",  source: "Graveyard Shift (story)", blurb: "Rats. Mill. A king-rat under the floor.",                                                                                 imdb: "tt0099697" },
  { title: "Sleepwalkers",            year: 1992, type: "film",       director: "Mick Garris",         source: "Sleepwalkers (screenplay)", blurb: "Original King script. Cat-creature shapeshifters in Indiana.",                                                          imdb: "tt0105428" },
  { title: "The Lawnmower Man",       year: 1992, type: "film",       director: "Brett Leonard",       source: "The Lawnmower Man (story, contested)", blurb: "King successfully sued to get his name off the poster. The film was barely his.",                       imdb: "tt0104692" },
  { title: "Needful Things",          year: 1993, type: "film",       director: "Fraser C. Heston",    source: "Needful Things",          blurb: "Max von Sydow as Leland Gaunt. Bonnie Bedelia. Castle Rock burns.",                                                       imdb: "tt0107665" },
  { title: "The Dark Half",           year: 1993, type: "film",       director: "George A. Romero",    source: "The Dark Half",           blurb: "Sparrows. Timothy Hutton plays both halves.",                                                                            imdb: "tt0106948" },
  { title: "The Stand",               year: 1994, type: "miniseries", director: "Mick Garris",         source: "The Stand",               blurb: "Six hours of ABC. M-O-O-N spells miniseries.",                                                                            imdb: "tt0108941" },
  { title: "The Shawshank Redemption",year: 1994, type: "film",       director: "Frank Darabont",      source: "Rita Hayworth and Shawshank Redemption", blurb: "Did poorly in theaters. Lives on IMDB top 1.",                                                                 imdb: "tt0111161" },
  { title: "Dolores Claiborne",       year: 1995, type: "film",       director: "Taylor Hackford",     source: "Dolores Claiborne",       blurb: "Kathy Bates again. Jennifer Jason Leigh. The eclipse scene.",                                                              imdb: "tt0112883" },
  { title: "Thinner",                 year: 1996, type: "film",       director: "Tom Holland",         source: "Thinner",                 blurb: "King cameos as Dr. Bangor.",                                                                                              imdb: "tt0117895" },
  { title: "The Mangler",             year: 1995, type: "film",       director: "Tobe Hooper",         source: "The Mangler (story)",     blurb: "A haunted industrial laundry press. As silly as it sounds.",                                                              imdb: "tt0113896" },
  { title: "The Green Mile",          year: 1999, type: "film",       director: "Frank Darabont",      source: "The Green Mile",          blurb: "Four-hour death-row drama. Michael Clarke Duncan, Tom Hanks, the mouse.",                                                imdb: "tt0120689" },
  { title: "Hearts in Atlantis",      year: 2001, type: "film",       director: "Scott Hicks",         source: "Hearts in Atlantis",      blurb: "Anthony Hopkins as Ted Brautigan. Loose adaptation of the first novella.",                                              imdb: "tt0252501" },
  { title: "Dreamcatcher",            year: 2003, type: "film",       director: "Lawrence Kasdan",     source: "Dreamcatcher",            blurb: "Aliens, the Maine woods, Morgan Freeman with terrifying eyebrows.",                                                       imdb: "tt0290334" },
  { title: "Secret Window",           year: 2004, type: "film",       director: "David Koepp",         source: "Secret Window, Secret Garden", blurb: "Depp at the end of his stretch of playing not-quite-Depp characters.",                                                imdb: "tt0363988" },
  { title: "1408",                    year: 2007, type: "film",       director: "Mikael Håfström",     source: "1408 (story)",            blurb: "Cusack alone in a hotel room. One of the best post-2000 King adaptations.",                                              imdb: "tt0450385" },
  { title: "The Mist",                year: 2007, type: "film",       director: "Frank Darabont",      source: "The Mist",                blurb: "Darabont's third King film. The ending he changed. The ending King endorsed.",                                            imdb: "tt0884328" },
  { title: "1922",                    year: 2017, type: "film",       director: "Zak Hilditch",        source: "1922 (novella)",          blurb: "Netflix. Thomas Jane. Nebraska. Rats again.",                                                                            imdb: "tt6740832" },
  { title: "Gerald's Game",           year: 2017, type: "film",       director: "Mike Flanagan",       source: "Gerald's Game",           blurb: "The handcuffs movie. Carla Gugino monologue. The de-gloving scene.",                                                       imdb: "tt5645572" },
  { title: "IT (Chapter One)",        year: 2017, type: "film",       director: "Andy Muschietti",     source: "IT (children section)",   blurb: "Bill Skarsgård. $700M box office. The first half of the kids' book.",                                                     imdb: "tt1396484" },
  { title: "The Dark Tower",          year: 2017, type: "film",       director: "Nikolaj Arcel",       source: "The Dark Tower (sequel-as-reset)", blurb: "Idris Elba. McConaughey. Two hours. Universally rejected.",                                                       imdb: "tt1648190" },
  { title: "Doctor Sleep",            year: 2019, type: "film",       director: "Mike Flanagan",       source: "Doctor Sleep",            blurb: "Reconciles Kubrick + King. Ewan McGregor. Rebecca Ferguson.",                                                              imdb: "tt5052448" },
  { title: "IT Chapter Two",          year: 2019, type: "film",       director: "Andy Muschietti",     source: "IT (adult section)",      blurb: "Jessica Chastain, Bill Hader, Ransom Riggs cameo. The losers as adults.",                                                  imdb: "tt7349950" },
  { title: "Pet Sematary",            year: 2019, type: "film",       director: "Kevin Kölsch, Dennis Widmyer", source: "Pet Sematary",   blurb: "Remake. Major switch: Ellie comes back instead of Gage.",                                                                 imdb: "tt0846308" },
  { title: "Mr. Harrigan's Phone",    year: 2022, type: "film",       director: "John Lee Hancock",    source: "Mr. Harrigan's Phone (novella)", blurb: "Donald Sutherland. iPhone in a casket pocket.",                                                                  imdb: "tt15679400" },
  { title: "The Boogeyman",           year: 2023, type: "film",       director: "Rob Savage",          source: "The Boogeyman (story)",   blurb: "One of King's earliest stories, finally a movie.",                                                                        imdb: "tt5052474" },
  { title: "Salem's Lot",             year: 2024, type: "film",       director: "Gary Dauberman",      source: "'Salem's Lot",            blurb: "Theatrical-cut remake that lived on Max for three years before release.",                                                  imdb: "tt8773366" },
  { title: "The Life of Chuck",       year: 2024, type: "film",       director: "Mike Flanagan",       source: "If It Bleeds (novella)",  blurb: "Tom Hiddleston. Three acts in reverse. The dance scene.",                                                                  imdb: "tt30253473" },
  { title: "11.22.63",                year: 2016, type: "miniseries", director: "—",                   source: "11/22/63",                blurb: "Hulu, eight episodes. James Franco as Jake Epping. Time travel in a diner pantry.",                                       imdb: "tt2879552" },
  { title: "The Outsider",            year: 2020, type: "miniseries", director: "—",                   source: "The Outsider",            blurb: "HBO. Ben Mendelsohn. Holly Gibney enters the show universe.",                                                              imdb: "tt8550800" },
  { title: "Castle Rock",             year: 2018, type: "tv-series",  director: "—",                   source: "Castle Rock (universe)",  blurb: "Hulu. Two seasons. King characters mashed up — Annie Wilkes, Pop Merrill, Pangborn.",                                       imdb: "tt6548228" },
  { title: "Lisey's Story",           year: 2021, type: "miniseries", director: "Pablo Larraín",        source: "Lisey's Story",           blurb: "Apple TV+. Julianne Moore. King wrote every episode.",                                                                     imdb: "tt10314462" },
];
