name: castle_rock
version: '1.0.0'
config-version: 2

profile: castle_rock

model-paths: ["models"]
test-paths:  ["tests"]
seed-paths:  ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  castle_rock:
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: dynamic_table
      +target_lag: '1 hour'
      +snowflake_warehouse: castle_rock_wh
      +schema: gold
